// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/org/wikimedia/analytics/varnishkafka/logline.proto

package org.wikimedia.analytics.varnishkafka;

public final class Logline {
  private Logline() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogLineOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 kafka_offset = 1;
    /**
     * <code>required int64 kafka_offset = 1;</code>
     */
    boolean hasKafkaOffset();
    /**
     * <code>required int64 kafka_offset = 1;</code>
     */
    long getKafkaOffset();

    // required string host = 2;
    /**
     * <code>required string host = 2;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <code>required string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    // required int64 seq_num = 3;
    /**
     * <code>required int64 seq_num = 3;</code>
     */
    boolean hasSeqNum();
    /**
     * <code>required int64 seq_num = 3;</code>
     */
    long getSeqNum();

    // required string timestamp = 4;
    /**
     * <code>required string timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 4;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 4;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    // required float response = 5;
    /**
     * <code>required float response = 5;</code>
     */
    boolean hasResponse();
    /**
     * <code>required float response = 5;</code>
     */
    float getResponse();

    // required string ip = 6;
    /**
     * <code>required string ip = 6;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 6;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 6;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    // required string http_status = 7;
    /**
     * <code>required string http_status = 7;</code>
     */
    boolean hasHttpStatus();
    /**
     * <code>required string http_status = 7;</code>
     */
    java.lang.String getHttpStatus();
    /**
     * <code>required string http_status = 7;</code>
     */
    com.google.protobuf.ByteString
        getHttpStatusBytes();

    // required int32 bytes_sent = 8;
    /**
     * <code>required int32 bytes_sent = 8;</code>
     */
    boolean hasBytesSent();
    /**
     * <code>required int32 bytes_sent = 8;</code>
     */
    int getBytesSent();

    // required string request_method = 9;
    /**
     * <code>required string request_method = 9;</code>
     */
    boolean hasRequestMethod();
    /**
     * <code>required string request_method = 9;</code>
     */
    java.lang.String getRequestMethod();
    /**
     * <code>required string request_method = 9;</code>
     */
    com.google.protobuf.ByteString
        getRequestMethodBytes();

    // required string uri = 10;
    /**
     * <code>required string uri = 10;</code>
     */
    boolean hasUri();
    /**
     * <code>required string uri = 10;</code>
     */
    java.lang.String getUri();
    /**
     * <code>required string uri = 10;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    // required string proxy_host = 11;
    /**
     * <code>required string proxy_host = 11;</code>
     */
    boolean hasProxyHost();
    /**
     * <code>required string proxy_host = 11;</code>
     */
    java.lang.String getProxyHost();
    /**
     * <code>required string proxy_host = 11;</code>
     */
    com.google.protobuf.ByteString
        getProxyHostBytes();

    // required string mime_type = 12;
    /**
     * <code>required string mime_type = 12;</code>
     */
    boolean hasMimeType();
    /**
     * <code>required string mime_type = 12;</code>
     */
    java.lang.String getMimeType();
    /**
     * <code>required string mime_type = 12;</code>
     */
    com.google.protobuf.ByteString
        getMimeTypeBytes();

    // required string referer = 13;
    /**
     * <code>required string referer = 13;</code>
     */
    boolean hasReferer();
    /**
     * <code>required string referer = 13;</code>
     */
    java.lang.String getReferer();
    /**
     * <code>required string referer = 13;</code>
     */
    com.google.protobuf.ByteString
        getRefererBytes();

    // required string x_forwarded_for = 14;
    /**
     * <code>required string x_forwarded_for = 14;</code>
     */
    boolean hasXForwardedFor();
    /**
     * <code>required string x_forwarded_for = 14;</code>
     */
    java.lang.String getXForwardedFor();
    /**
     * <code>required string x_forwarded_for = 14;</code>
     */
    com.google.protobuf.ByteString
        getXForwardedForBytes();

    // required string user_agent = 15;
    /**
     * <code>required string user_agent = 15;</code>
     */
    boolean hasUserAgent();
    /**
     * <code>required string user_agent = 15;</code>
     */
    java.lang.String getUserAgent();
    /**
     * <code>required string user_agent = 15;</code>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    // required string accept_language = 16;
    /**
     * <code>required string accept_language = 16;</code>
     */
    boolean hasAcceptLanguage();
    /**
     * <code>required string accept_language = 16;</code>
     */
    java.lang.String getAcceptLanguage();
    /**
     * <code>required string accept_language = 16;</code>
     */
    com.google.protobuf.ByteString
        getAcceptLanguageBytes();

    // required string x_analytics = 17;
    /**
     * <code>required string x_analytics = 17;</code>
     */
    boolean hasXAnalytics();
    /**
     * <code>required string x_analytics = 17;</code>
     */
    java.lang.String getXAnalytics();
    /**
     * <code>required string x_analytics = 17;</code>
     */
    com.google.protobuf.ByteString
        getXAnalyticsBytes();
  }
  /**
   * Protobuf type {@code org.wikimedia.analytics.varnishkafka.LogLine}
   */
  public static final class LogLine extends
      com.google.protobuf.GeneratedMessage
      implements LogLineOrBuilder {
    // Use LogLine.newBuilder() to construct.
    private LogLine(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogLine(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogLine defaultInstance;
    public static LogLine getDefaultInstance() {
      return defaultInstance;
    }

    public LogLine getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogLine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              kafkaOffset_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              host_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seqNum_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readBytes();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              response_ = input.readFloat();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              ip_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              httpStatus_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              bytesSent_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              requestMethod_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              uri_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              proxyHost_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              mimeType_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              referer_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              xForwardedFor_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              userAgent_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              acceptLanguage_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              xAnalytics_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wikimedia.analytics.varnishkafka.Logline.internal_static_org_wikimedia_analytics_varnishkafka_LogLine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wikimedia.analytics.varnishkafka.Logline.internal_static_org_wikimedia_analytics_varnishkafka_LogLine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wikimedia.analytics.varnishkafka.Logline.LogLine.class, org.wikimedia.analytics.varnishkafka.Logline.LogLine.Builder.class);
    }

    public static com.google.protobuf.Parser<LogLine> PARSER =
        new com.google.protobuf.AbstractParser<LogLine>() {
      public LogLine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogLine(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogLine> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 kafka_offset = 1;
    public static final int KAFKA_OFFSET_FIELD_NUMBER = 1;
    private long kafkaOffset_;
    /**
     * <code>required int64 kafka_offset = 1;</code>
     */
    public boolean hasKafkaOffset() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 kafka_offset = 1;</code>
     */
    public long getKafkaOffset() {
      return kafkaOffset_;
    }

    // required string host = 2;
    public static final int HOST_FIELD_NUMBER = 2;
    private java.lang.Object host_;
    /**
     * <code>required string host = 2;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string host = 2;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 seq_num = 3;
    public static final int SEQ_NUM_FIELD_NUMBER = 3;
    private long seqNum_;
    /**
     * <code>required int64 seq_num = 3;</code>
     */
    public boolean hasSeqNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 seq_num = 3;</code>
     */
    public long getSeqNum() {
      return seqNum_;
    }

    // required string timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private java.lang.Object timestamp_;
    /**
     * <code>required string timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string timestamp = 4;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required float response = 5;
    public static final int RESPONSE_FIELD_NUMBER = 5;
    private float response_;
    /**
     * <code>required float response = 5;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float response = 5;</code>
     */
    public float getResponse() {
      return response_;
    }

    // required string ip = 6;
    public static final int IP_FIELD_NUMBER = 6;
    private java.lang.Object ip_;
    /**
     * <code>required string ip = 6;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string ip = 6;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string http_status = 7;
    public static final int HTTP_STATUS_FIELD_NUMBER = 7;
    private java.lang.Object httpStatus_;
    /**
     * <code>required string http_status = 7;</code>
     */
    public boolean hasHttpStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string http_status = 7;</code>
     */
    public java.lang.String getHttpStatus() {
      java.lang.Object ref = httpStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          httpStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string http_status = 7;</code>
     */
    public com.google.protobuf.ByteString
        getHttpStatusBytes() {
      java.lang.Object ref = httpStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 bytes_sent = 8;
    public static final int BYTES_SENT_FIELD_NUMBER = 8;
    private int bytesSent_;
    /**
     * <code>required int32 bytes_sent = 8;</code>
     */
    public boolean hasBytesSent() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 bytes_sent = 8;</code>
     */
    public int getBytesSent() {
      return bytesSent_;
    }

    // required string request_method = 9;
    public static final int REQUEST_METHOD_FIELD_NUMBER = 9;
    private java.lang.Object requestMethod_;
    /**
     * <code>required string request_method = 9;</code>
     */
    public boolean hasRequestMethod() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string request_method = 9;</code>
     */
    public java.lang.String getRequestMethod() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestMethod_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string request_method = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMethodBytes() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string uri = 10;
    public static final int URI_FIELD_NUMBER = 10;
    private java.lang.Object uri_;
    /**
     * <code>required string uri = 10;</code>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string uri = 10;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uri = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string proxy_host = 11;
    public static final int PROXY_HOST_FIELD_NUMBER = 11;
    private java.lang.Object proxyHost_;
    /**
     * <code>required string proxy_host = 11;</code>
     */
    public boolean hasProxyHost() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string proxy_host = 11;</code>
     */
    public java.lang.String getProxyHost() {
      java.lang.Object ref = proxyHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          proxyHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string proxy_host = 11;</code>
     */
    public com.google.protobuf.ByteString
        getProxyHostBytes() {
      java.lang.Object ref = proxyHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proxyHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string mime_type = 12;
    public static final int MIME_TYPE_FIELD_NUMBER = 12;
    private java.lang.Object mimeType_;
    /**
     * <code>required string mime_type = 12;</code>
     */
    public boolean hasMimeType() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string mime_type = 12;</code>
     */
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mimeType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mime_type = 12;</code>
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string referer = 13;
    public static final int REFERER_FIELD_NUMBER = 13;
    private java.lang.Object referer_;
    /**
     * <code>required string referer = 13;</code>
     */
    public boolean hasReferer() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required string referer = 13;</code>
     */
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string referer = 13;</code>
     */
    public com.google.protobuf.ByteString
        getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string x_forwarded_for = 14;
    public static final int X_FORWARDED_FOR_FIELD_NUMBER = 14;
    private java.lang.Object xForwardedFor_;
    /**
     * <code>required string x_forwarded_for = 14;</code>
     */
    public boolean hasXForwardedFor() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required string x_forwarded_for = 14;</code>
     */
    public java.lang.String getXForwardedFor() {
      java.lang.Object ref = xForwardedFor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          xForwardedFor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string x_forwarded_for = 14;</code>
     */
    public com.google.protobuf.ByteString
        getXForwardedForBytes() {
      java.lang.Object ref = xForwardedFor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xForwardedFor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string user_agent = 15;
    public static final int USER_AGENT_FIELD_NUMBER = 15;
    private java.lang.Object userAgent_;
    /**
     * <code>required string user_agent = 15;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required string user_agent = 15;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_agent = 15;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string accept_language = 16;
    public static final int ACCEPT_LANGUAGE_FIELD_NUMBER = 16;
    private java.lang.Object acceptLanguage_;
    /**
     * <code>required string accept_language = 16;</code>
     */
    public boolean hasAcceptLanguage() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required string accept_language = 16;</code>
     */
    public java.lang.String getAcceptLanguage() {
      java.lang.Object ref = acceptLanguage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          acceptLanguage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string accept_language = 16;</code>
     */
    public com.google.protobuf.ByteString
        getAcceptLanguageBytes() {
      java.lang.Object ref = acceptLanguage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptLanguage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string x_analytics = 17;
    public static final int X_ANALYTICS_FIELD_NUMBER = 17;
    private java.lang.Object xAnalytics_;
    /**
     * <code>required string x_analytics = 17;</code>
     */
    public boolean hasXAnalytics() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required string x_analytics = 17;</code>
     */
    public java.lang.String getXAnalytics() {
      java.lang.Object ref = xAnalytics_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          xAnalytics_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string x_analytics = 17;</code>
     */
    public com.google.protobuf.ByteString
        getXAnalyticsBytes() {
      java.lang.Object ref = xAnalytics_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xAnalytics_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      kafkaOffset_ = 0L;
      host_ = "";
      seqNum_ = 0L;
      timestamp_ = "";
      response_ = 0F;
      ip_ = "";
      httpStatus_ = "";
      bytesSent_ = 0;
      requestMethod_ = "";
      uri_ = "";
      proxyHost_ = "";
      mimeType_ = "";
      referer_ = "";
      xForwardedFor_ = "";
      userAgent_ = "";
      acceptLanguage_ = "";
      xAnalytics_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKafkaOffset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeqNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHttpStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBytesSent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProxyHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMimeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReferer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXForwardedFor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserAgent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAcceptLanguage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasXAnalytics()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, kafkaOffset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHostBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, seqNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, response_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getHttpStatusBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, bytesSent_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getRequestMethodBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getUriBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getProxyHostBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getMimeTypeBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getRefererBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getXForwardedForBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getAcceptLanguageBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getXAnalyticsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, kafkaOffset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHostBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, seqNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, response_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getIpBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getHttpStatusBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, bytesSent_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getRequestMethodBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUriBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getProxyHostBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getMimeTypeBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getRefererBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getXForwardedForBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getAcceptLanguageBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getXAnalyticsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.wikimedia.analytics.varnishkafka.Logline.LogLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.wikimedia.analytics.varnishkafka.Logline.LogLine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.wikimedia.analytics.varnishkafka.LogLine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.wikimedia.analytics.varnishkafka.Logline.LogLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.wikimedia.analytics.varnishkafka.Logline.internal_static_org_wikimedia_analytics_varnishkafka_LogLine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.wikimedia.analytics.varnishkafka.Logline.internal_static_org_wikimedia_analytics_varnishkafka_LogLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.wikimedia.analytics.varnishkafka.Logline.LogLine.class, org.wikimedia.analytics.varnishkafka.Logline.LogLine.Builder.class);
      }

      // Construct using org.wikimedia.analytics.varnishkafka.Logline.LogLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        kafkaOffset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seqNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        response_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        httpStatus_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        bytesSent_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        requestMethod_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        proxyHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        mimeType_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        referer_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        xForwardedFor_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        acceptLanguage_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        xAnalytics_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.wikimedia.analytics.varnishkafka.Logline.internal_static_org_wikimedia_analytics_varnishkafka_LogLine_descriptor;
      }

      public org.wikimedia.analytics.varnishkafka.Logline.LogLine getDefaultInstanceForType() {
        return org.wikimedia.analytics.varnishkafka.Logline.LogLine.getDefaultInstance();
      }

      public org.wikimedia.analytics.varnishkafka.Logline.LogLine build() {
        org.wikimedia.analytics.varnishkafka.Logline.LogLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.wikimedia.analytics.varnishkafka.Logline.LogLine buildPartial() {
        org.wikimedia.analytics.varnishkafka.Logline.LogLine result = new org.wikimedia.analytics.varnishkafka.Logline.LogLine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.kafkaOffset_ = kafkaOffset_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seqNum_ = seqNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.response_ = response_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.httpStatus_ = httpStatus_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bytesSent_ = bytesSent_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.requestMethod_ = requestMethod_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.proxyHost_ = proxyHost_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.mimeType_ = mimeType_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.referer_ = referer_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.xForwardedFor_ = xForwardedFor_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.acceptLanguage_ = acceptLanguage_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.xAnalytics_ = xAnalytics_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.wikimedia.analytics.varnishkafka.Logline.LogLine) {
          return mergeFrom((org.wikimedia.analytics.varnishkafka.Logline.LogLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.wikimedia.analytics.varnishkafka.Logline.LogLine other) {
        if (other == org.wikimedia.analytics.varnishkafka.Logline.LogLine.getDefaultInstance()) return this;
        if (other.hasKafkaOffset()) {
          setKafkaOffset(other.getKafkaOffset());
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000002;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasSeqNum()) {
          setSeqNum(other.getSeqNum());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000008;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000020;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasHttpStatus()) {
          bitField0_ |= 0x00000040;
          httpStatus_ = other.httpStatus_;
          onChanged();
        }
        if (other.hasBytesSent()) {
          setBytesSent(other.getBytesSent());
        }
        if (other.hasRequestMethod()) {
          bitField0_ |= 0x00000100;
          requestMethod_ = other.requestMethod_;
          onChanged();
        }
        if (other.hasUri()) {
          bitField0_ |= 0x00000200;
          uri_ = other.uri_;
          onChanged();
        }
        if (other.hasProxyHost()) {
          bitField0_ |= 0x00000400;
          proxyHost_ = other.proxyHost_;
          onChanged();
        }
        if (other.hasMimeType()) {
          bitField0_ |= 0x00000800;
          mimeType_ = other.mimeType_;
          onChanged();
        }
        if (other.hasReferer()) {
          bitField0_ |= 0x00001000;
          referer_ = other.referer_;
          onChanged();
        }
        if (other.hasXForwardedFor()) {
          bitField0_ |= 0x00002000;
          xForwardedFor_ = other.xForwardedFor_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00004000;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.hasAcceptLanguage()) {
          bitField0_ |= 0x00008000;
          acceptLanguage_ = other.acceptLanguage_;
          onChanged();
        }
        if (other.hasXAnalytics()) {
          bitField0_ |= 0x00010000;
          xAnalytics_ = other.xAnalytics_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKafkaOffset()) {
          
          return false;
        }
        if (!hasHost()) {
          
          return false;
        }
        if (!hasSeqNum()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasResponse()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasHttpStatus()) {
          
          return false;
        }
        if (!hasBytesSent()) {
          
          return false;
        }
        if (!hasRequestMethod()) {
          
          return false;
        }
        if (!hasUri()) {
          
          return false;
        }
        if (!hasProxyHost()) {
          
          return false;
        }
        if (!hasMimeType()) {
          
          return false;
        }
        if (!hasReferer()) {
          
          return false;
        }
        if (!hasXForwardedFor()) {
          
          return false;
        }
        if (!hasUserAgent()) {
          
          return false;
        }
        if (!hasAcceptLanguage()) {
          
          return false;
        }
        if (!hasXAnalytics()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.wikimedia.analytics.varnishkafka.Logline.LogLine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.wikimedia.analytics.varnishkafka.Logline.LogLine) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 kafka_offset = 1;
      private long kafkaOffset_ ;
      /**
       * <code>required int64 kafka_offset = 1;</code>
       */
      public boolean hasKafkaOffset() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 kafka_offset = 1;</code>
       */
      public long getKafkaOffset() {
        return kafkaOffset_;
      }
      /**
       * <code>required int64 kafka_offset = 1;</code>
       */
      public Builder setKafkaOffset(long value) {
        bitField0_ |= 0x00000001;
        kafkaOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 kafka_offset = 1;</code>
       */
      public Builder clearKafkaOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        kafkaOffset_ = 0L;
        onChanged();
        return this;
      }

      // required string host = 2;
      private java.lang.Object host_ = "";
      /**
       * <code>required string host = 2;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string host = 2;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 2;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        host_ = value;
        onChanged();
        return this;
      }

      // required int64 seq_num = 3;
      private long seqNum_ ;
      /**
       * <code>required int64 seq_num = 3;</code>
       */
      public boolean hasSeqNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 seq_num = 3;</code>
       */
      public long getSeqNum() {
        return seqNum_;
      }
      /**
       * <code>required int64 seq_num = 3;</code>
       */
      public Builder setSeqNum(long value) {
        bitField0_ |= 0x00000004;
        seqNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 seq_num = 3;</code>
       */
      public Builder clearSeqNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seqNum_ = 0L;
        onChanged();
        return this;
      }

      // required string timestamp = 4;
      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string timestamp = 4;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 4;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 4;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }

      // required float response = 5;
      private float response_ ;
      /**
       * <code>required float response = 5;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float response = 5;</code>
       */
      public float getResponse() {
        return response_;
      }
      /**
       * <code>required float response = 5;</code>
       */
      public Builder setResponse(float value) {
        bitField0_ |= 0x00000010;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float response = 5;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000010);
        response_ = 0F;
        onChanged();
        return this;
      }

      // required string ip = 6;
      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 6;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string ip = 6;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 6;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 6;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 6;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ip_ = value;
        onChanged();
        return this;
      }

      // required string http_status = 7;
      private java.lang.Object httpStatus_ = "";
      /**
       * <code>required string http_status = 7;</code>
       */
      public boolean hasHttpStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string http_status = 7;</code>
       */
      public java.lang.String getHttpStatus() {
        java.lang.Object ref = httpStatus_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          httpStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string http_status = 7;</code>
       */
      public com.google.protobuf.ByteString
          getHttpStatusBytes() {
        java.lang.Object ref = httpStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string http_status = 7;</code>
       */
      public Builder setHttpStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        httpStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string http_status = 7;</code>
       */
      public Builder clearHttpStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        httpStatus_ = getDefaultInstance().getHttpStatus();
        onChanged();
        return this;
      }
      /**
       * <code>required string http_status = 7;</code>
       */
      public Builder setHttpStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        httpStatus_ = value;
        onChanged();
        return this;
      }

      // required int32 bytes_sent = 8;
      private int bytesSent_ ;
      /**
       * <code>required int32 bytes_sent = 8;</code>
       */
      public boolean hasBytesSent() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 bytes_sent = 8;</code>
       */
      public int getBytesSent() {
        return bytesSent_;
      }
      /**
       * <code>required int32 bytes_sent = 8;</code>
       */
      public Builder setBytesSent(int value) {
        bitField0_ |= 0x00000080;
        bytesSent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bytes_sent = 8;</code>
       */
      public Builder clearBytesSent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bytesSent_ = 0;
        onChanged();
        return this;
      }

      // required string request_method = 9;
      private java.lang.Object requestMethod_ = "";
      /**
       * <code>required string request_method = 9;</code>
       */
      public boolean hasRequestMethod() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string request_method = 9;</code>
       */
      public java.lang.String getRequestMethod() {
        java.lang.Object ref = requestMethod_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string request_method = 9;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMethodBytes() {
        java.lang.Object ref = requestMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string request_method = 9;</code>
       */
      public Builder setRequestMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        requestMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string request_method = 9;</code>
       */
      public Builder clearRequestMethod() {
        bitField0_ = (bitField0_ & ~0x00000100);
        requestMethod_ = getDefaultInstance().getRequestMethod();
        onChanged();
        return this;
      }
      /**
       * <code>required string request_method = 9;</code>
       */
      public Builder setRequestMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        requestMethod_ = value;
        onChanged();
        return this;
      }

      // required string uri = 10;
      private java.lang.Object uri_ = "";
      /**
       * <code>required string uri = 10;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string uri = 10;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uri = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uri = 10;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 10;</code>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000200);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 10;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        uri_ = value;
        onChanged();
        return this;
      }

      // required string proxy_host = 11;
      private java.lang.Object proxyHost_ = "";
      /**
       * <code>required string proxy_host = 11;</code>
       */
      public boolean hasProxyHost() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string proxy_host = 11;</code>
       */
      public java.lang.String getProxyHost() {
        java.lang.Object ref = proxyHost_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          proxyHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string proxy_host = 11;</code>
       */
      public com.google.protobuf.ByteString
          getProxyHostBytes() {
        java.lang.Object ref = proxyHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proxyHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string proxy_host = 11;</code>
       */
      public Builder setProxyHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        proxyHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string proxy_host = 11;</code>
       */
      public Builder clearProxyHost() {
        bitField0_ = (bitField0_ & ~0x00000400);
        proxyHost_ = getDefaultInstance().getProxyHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string proxy_host = 11;</code>
       */
      public Builder setProxyHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        proxyHost_ = value;
        onChanged();
        return this;
      }

      // required string mime_type = 12;
      private java.lang.Object mimeType_ = "";
      /**
       * <code>required string mime_type = 12;</code>
       */
      public boolean hasMimeType() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string mime_type = 12;</code>
       */
      public java.lang.String getMimeType() {
        java.lang.Object ref = mimeType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mimeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mime_type = 12;</code>
       */
      public com.google.protobuf.ByteString
          getMimeTypeBytes() {
        java.lang.Object ref = mimeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mimeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mime_type = 12;</code>
       */
      public Builder setMimeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        mimeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mime_type = 12;</code>
       */
      public Builder clearMimeType() {
        bitField0_ = (bitField0_ & ~0x00000800);
        mimeType_ = getDefaultInstance().getMimeType();
        onChanged();
        return this;
      }
      /**
       * <code>required string mime_type = 12;</code>
       */
      public Builder setMimeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        mimeType_ = value;
        onChanged();
        return this;
      }

      // required string referer = 13;
      private java.lang.Object referer_ = "";
      /**
       * <code>required string referer = 13;</code>
       */
      public boolean hasReferer() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required string referer = 13;</code>
       */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string referer = 13;</code>
       */
      public com.google.protobuf.ByteString
          getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string referer = 13;</code>
       */
      public Builder setReferer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        referer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string referer = 13;</code>
       */
      public Builder clearReferer() {
        bitField0_ = (bitField0_ & ~0x00001000);
        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /**
       * <code>required string referer = 13;</code>
       */
      public Builder setRefererBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        referer_ = value;
        onChanged();
        return this;
      }

      // required string x_forwarded_for = 14;
      private java.lang.Object xForwardedFor_ = "";
      /**
       * <code>required string x_forwarded_for = 14;</code>
       */
      public boolean hasXForwardedFor() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required string x_forwarded_for = 14;</code>
       */
      public java.lang.String getXForwardedFor() {
        java.lang.Object ref = xForwardedFor_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          xForwardedFor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string x_forwarded_for = 14;</code>
       */
      public com.google.protobuf.ByteString
          getXForwardedForBytes() {
        java.lang.Object ref = xForwardedFor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xForwardedFor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string x_forwarded_for = 14;</code>
       */
      public Builder setXForwardedFor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        xForwardedFor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string x_forwarded_for = 14;</code>
       */
      public Builder clearXForwardedFor() {
        bitField0_ = (bitField0_ & ~0x00002000);
        xForwardedFor_ = getDefaultInstance().getXForwardedFor();
        onChanged();
        return this;
      }
      /**
       * <code>required string x_forwarded_for = 14;</code>
       */
      public Builder setXForwardedForBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        xForwardedFor_ = value;
        onChanged();
        return this;
      }

      // required string user_agent = 15;
      private java.lang.Object userAgent_ = "";
      /**
       * <code>required string user_agent = 15;</code>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required string user_agent = 15;</code>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_agent = 15;</code>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_agent = 15;</code>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_agent = 15;</code>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00004000);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_agent = 15;</code>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        userAgent_ = value;
        onChanged();
        return this;
      }

      // required string accept_language = 16;
      private java.lang.Object acceptLanguage_ = "";
      /**
       * <code>required string accept_language = 16;</code>
       */
      public boolean hasAcceptLanguage() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required string accept_language = 16;</code>
       */
      public java.lang.String getAcceptLanguage() {
        java.lang.Object ref = acceptLanguage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          acceptLanguage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string accept_language = 16;</code>
       */
      public com.google.protobuf.ByteString
          getAcceptLanguageBytes() {
        java.lang.Object ref = acceptLanguage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          acceptLanguage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string accept_language = 16;</code>
       */
      public Builder setAcceptLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        acceptLanguage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string accept_language = 16;</code>
       */
      public Builder clearAcceptLanguage() {
        bitField0_ = (bitField0_ & ~0x00008000);
        acceptLanguage_ = getDefaultInstance().getAcceptLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>required string accept_language = 16;</code>
       */
      public Builder setAcceptLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        acceptLanguage_ = value;
        onChanged();
        return this;
      }

      // required string x_analytics = 17;
      private java.lang.Object xAnalytics_ = "";
      /**
       * <code>required string x_analytics = 17;</code>
       */
      public boolean hasXAnalytics() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required string x_analytics = 17;</code>
       */
      public java.lang.String getXAnalytics() {
        java.lang.Object ref = xAnalytics_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          xAnalytics_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string x_analytics = 17;</code>
       */
      public com.google.protobuf.ByteString
          getXAnalyticsBytes() {
        java.lang.Object ref = xAnalytics_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          xAnalytics_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string x_analytics = 17;</code>
       */
      public Builder setXAnalytics(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        xAnalytics_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string x_analytics = 17;</code>
       */
      public Builder clearXAnalytics() {
        bitField0_ = (bitField0_ & ~0x00010000);
        xAnalytics_ = getDefaultInstance().getXAnalytics();
        onChanged();
        return this;
      }
      /**
       * <code>required string x_analytics = 17;</code>
       */
      public Builder setXAnalyticsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        xAnalytics_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.wikimedia.analytics.varnishkafka.LogLine)
    }

    static {
      defaultInstance = new LogLine(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.wikimedia.analytics.varnishkafka.LogLine)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_wikimedia_analytics_varnishkafka_LogLine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_wikimedia_analytics_varnishkafka_LogLine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@src/main/java/org/wikimedia/analytics/" +
      "varnishkafka/logline.proto\022$org.wikimedi" +
      "a.analytics.varnishkafka\"\320\002\n\007LogLine\022\024\n\014" +
      "kafka_offset\030\001 \002(\003\022\014\n\004host\030\002 \002(\t\022\017\n\007seq_" +
      "num\030\003 \002(\003\022\021\n\ttimestamp\030\004 \002(\t\022\020\n\010response" +
      "\030\005 \002(\002\022\n\n\002ip\030\006 \002(\t\022\023\n\013http_status\030\007 \002(\t\022" +
      "\022\n\nbytes_sent\030\010 \002(\005\022\026\n\016request_method\030\t " +
      "\002(\t\022\013\n\003uri\030\n \002(\t\022\022\n\nproxy_host\030\013 \002(\t\022\021\n\t" +
      "mime_type\030\014 \002(\t\022\017\n\007referer\030\r \002(\t\022\027\n\017x_fo" +
      "rwarded_for\030\016 \002(\t\022\022\n\nuser_agent\030\017 \002(\t\022\027\n",
      "\017accept_language\030\020 \002(\t\022\023\n\013x_analytics\030\021 " +
      "\002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_wikimedia_analytics_varnishkafka_LogLine_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_wikimedia_analytics_varnishkafka_LogLine_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_wikimedia_analytics_varnishkafka_LogLine_descriptor,
              new java.lang.String[] { "KafkaOffset", "Host", "SeqNum", "Timestamp", "Response", "Ip", "HttpStatus", "BytesSent", "RequestMethod", "Uri", "ProxyHost", "MimeType", "Referer", "XForwardedFor", "UserAgent", "AcceptLanguage", "XAnalytics", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
